name: 'SDM Access GH Action'
description: 'Manage access to strongDM resources via Github Actions'
inputs:
  ag-random-key-job-name:
    description: 'Workflow Job name responsible for printing the random UUID (v4) key in the format "###random_access_key=RANDOM_UUID_KEY###"'
    required: true
  ag-random-key:
    description: 'Access Granter random access key'
    required: true
  ag-secret:
    description: 'Access Granter shared secret'
    required: true
  server-host:
    description: 'Access Granter proxy host address'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RUN_ID: ${{ GITHUB_RUN_ID }}
    RANDOM_KEY_JOB_NAME: ${{ inputs.ag-random-key-job-name }}
    AG_RANDOM_KEY: ${{ inputs.ag-random-key }}
    AG_SECRET: ${{ inputs.ag-secret }}
    SERVER_HOST: ${{ inputs.server-host }}
