name: 'SDM Access GH Action'
description: 'Manage access to strongDM resources via Github Actions'
inputs:
  run-id:
    description: 'Github Action Workflow run id'
    required: true
  ag-random-access-key:
    description: 'Access Granter random access key'
    required: true
  ag-secret:
    description: 'Access Granter shared secret'
    required: true
  server-host:
    description: 'Access Granter proxy host address'
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo apt install python3-pip
      shell: bash
    - run: pip install -r requirements.txt
      shell: bash
    - run: bash entrypoint.sh
      shell: bash
      env:
        RUN_ID: ${{ inputs.run-id }}
        AG_RANDOM_ACCESS_KEY: ${{ inputs.ag-random-access-key }}
        AG_SECRET: ${{ inputs.ag-secret }}
        SERVER_HOST: ${{ inputs.server-host }}
